# Generated by Django 3.2.8 on 2021-10-25 16:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='phone_no',
        ),
        migrations.AddField(
            model_name='myprofile',
            name='phoneno',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='followuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='pic',
            field=models.ImageField(null=True, upload_to='image\\'),
        ),
        migrations.AlterField(
            model_name='mypost',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='social.myprofile'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='age',
            field=models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=20),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='pic',
            field=models.ImageField(null=True, upload_to='image\\'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='status',
            field=models.CharField(choices=[('single', 'single'), ('married', 'married')], default='single', max_length=20),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='flag',
            field=models.CharField(blank=True, choices=[('racist', 'racist'), ('abusing', 'abusing')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='msg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
