# Generated by Django 3.2.8 on 2021-10-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20211025_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='email',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
